
import { Lesson, SuggestedReply } from './types';

export const LESSON_CATEGORIES = [
  '基础篇',
  'N5语法',
  'N4语法',
  'N3语法',
  'N2语法',
  'N1语法'
];

// Optimized for readability: Dark text (blue-950) on light backgrounds, White text on dark backgrounds.
// Colors are now softer (500/400) or deeper (950).
export const CATEGORY_META: Record<string, { description: string; color: string; iconBg: string; level: string; borderColor: string }> = {
  '基础篇': { 
    description: '五十音图与日语的底层逻辑', 
    color: 'text-blue-950', 
    iconBg: 'bg-white',
    level: 'Basic',
    borderColor: 'border-blue-950'
  },
  'N5语法': { 
    description: '120个核心语法点，通关生存日语', 
    color: 'text-white', 
    iconBg: 'bg-blue-500',
    level: 'N5',
    borderColor: 'border-blue-950'
  },
  'N4语法': { 
    description: '动词变形与基础复句', 
    color: 'text-blue-950', 
    iconBg: 'bg-blue-200',
    level: 'N4',
    borderColor: 'border-blue-950'
  },
  'N3语法': { 
    description: '日常交流与进阶表达', 
    color: 'text-white', 
    iconBg: 'bg-blue-600',
    level: 'N3',
    borderColor: 'border-blue-950'
  },
  'N2语法': { 
    description: '商务日语与抽象逻辑', 
    color: 'text-blue-950', 
    iconBg: 'bg-blue-100',
    level: 'N2',
    borderColor: 'border-blue-950'
  },
  'N1语法': { 
    description: '生硬书面语与高阶修辞', 
    color: 'text-white', 
    iconBg: 'bg-blue-400', // Changed from bg-blue-800 to lighter blue
    level: 'N1',
    borderColor: 'border-blue-950'
  },
};

let lessons: Lesson[] = [
  // --- 基础篇 (Expanded to 10 lessons) ---
  {
    id: 'b-1',
    category: '基础篇',
    title: '元音定乾坤',
    subtitle: 'a i u e o 的秘密',
    duration: '5 分钟',
    initialPrompt: 'Sensei, 请从底层逻辑教我日语发音。为什么说只要掌握 a i u e o 这五个元音，就能搞定所有发音？'
  },
  {
    id: 'b-2',
    category: '基础篇',
    title: '五十音图的本质',
    subtitle: '不是字母表，是声音地图',
    duration: '8 分钟',
    initialPrompt: 'Sensei, 五十音图好难背啊！有没有什么诀窍？它到底是个什么东西？'
  },
  {
    id: 'b-3',
    category: '基础篇',
    title: '声音的“变身”',
    subtitle: '清音、浊音与半浊音',
    duration: '6 分钟',
    initialPrompt: 'Sensei, “か” (ka) 怎么有时候会念成 “が” (ga)？请教我日语的浊音和半浊音。'
  },
  {
    id: 'b-4',
    category: '基础篇',
    title: '声音的“合体”',
    subtitle: '拗音的组合逻辑',
    duration: '6 分钟',
    initialPrompt: 'Sensei, 像 “きゃ” (kya) 这种两个假名拼成一个音的“拗音”是什么原理？'
  },
  {
    id: 'b-5',
    category: '基础篇',
    title: '三种特殊节拍',
    subtitle: '长音、促音、拨音',
    duration: '8 分钟',
    initialPrompt: 'Sensei, 日语里的长音、促音（小っ）和拨音（ん）到底怎么发？它们很重要吗？'
  },
  {
    id: 'b-6',
    category: '基础篇',
    title: '另一个“我”',
    subtitle: '片假名的使用场景',
    duration: '7 分钟',
    initialPrompt: 'Sensei, 为什么日本人有平假名还要用片假名？什么时候该用哪个？'
  },
  {
    id: 'b-7',
    category: '基础篇',
    title: '思维的倒转',
    subtitle: '“我饭吃”的语序逻辑',
    duration: '8 分钟',
    initialPrompt: 'Sensei, 请教我日语句子的核心逻辑。为什么说日语是“必须听到最后才能懂”的语言？这个 SOV 语序到底是怎么回事？'
  },
  {
    id: 'b-8',
    category: '基础篇',
    title: '灵魂粒子',
    subtitle: '助词：日语的粘合剂',
    duration: '10 分钟',
    initialPrompt: 'Sensei, 我听说日语有很多像‘は’‘が’‘を’这样的小字，它们叫“助词”。它们到底是什么？为什么说没有它们，句子就散架了？请从根本上给我讲讲这个概念。'
  },
  {
    id: 'b-9',
    category: '基础篇',
    title: '谁在说话？',
    subtitle: '日语为何总省略主语',
    duration: '7 分钟',
    initialPrompt: 'Sensei, 我看日剧发现他们说话很少说‘我’、‘你’。为什么主语总是不见？难道不会搞混吗？请教我这个语言习惯背后的逻辑。'
  },
  {
    id: 'b-10',
    category: '基础篇',
    title: '礼貌的艺术',
    subtitle: 'です/ます体 vs 普通体',
    duration: '7 分钟',
    initialPrompt: 'Sensei, 为什么有时候结尾是“です”，有时候又不是？请给我讲讲日语的礼貌体（敬体）和普通体（简体）的基本概念。'
  },

  // --- N5 120 课 ---
  { id: 'n5-1', category: 'N5语法', title: '我是谁？', subtitle: '名词1+は+名词2+です/ではありません', duration: '5m', initialPrompt: '教我用日语自我介绍和否定，讲解 AはBです 句型。' },
  { id: 'n5-2', category: 'N5语法', title: '昨日的我', subtitle: '名词1+は+名词2+でした/ではありませんでした', duration: '5m', initialPrompt: '教我日语名词句的过去式。' },
  { id: 'n5-3', category: 'N5语法', title: '朋友之间别客气', subtitle: '名词1+は+名词2+だ/ではない', duration: '4m', initialPrompt: '教我日语名词句的简体（普通形），用于朋友对话。' },
  { id: 'n5-4', category: 'N5语法', title: '那些年', subtitle: '名词1+は+名词2+だった/ではなかった', duration: '4m', initialPrompt: '教我日语名词句简体的过去式。' },
  { id: 'n5-5', category: 'N5语法', title: '是这样吗？', subtitle: '名词1+は+名词2+ですか/でしたか', duration: '4m', initialPrompt: '教我如何用日语提问（疑问句）。' },
  { id: 'n5-6', category: 'N5语法', title: '我是老师也是学生', subtitle: '名词1+は+名词2+で、名词3です', duration: '5m', initialPrompt: '教我用“で”连接两个名词句子（中顿）。' },
  { id: 'n5-7', category: 'N5语法', title: '这个那个到底是哪个', subtitle: 'これ、それ、あれ、どれ', duration: '5m', initialPrompt: '教我日语的指示代词（事物）：これ、それ、あれ、どれ。' },
  { id: 'n5-8', category: 'N5语法', title: '特指这个东西', subtitle: 'この、その、あの、どの', duration: '5m', initialPrompt: '教我日语的连体词：この、その、あの、どの。' },
  { id: 'n5-9', category: 'N5语法', title: '我在哪？', subtitle: 'ここ、そこ、あそこ、どこ', duration: '5m', initialPrompt: '教我日语的地点指示词：ここ、そこ、あそこ、どこ。' },
  { id: 'n5-10', category: 'N5语法', title: '就这样办', subtitle: 'こう、そう、ああ、どう', duration: '5m', initialPrompt: '教我日语的副词性指示词：こう、そう、ああ、どう。' },
  
  { id: 'n5-11', category: 'N5语法', title: '这边请', subtitle: 'こちら、そちら、あちら、どちら', duration: '5m', initialPrompt: '教我日语的方向/礼貌指示词：こちら、そちら、あちら、どちら。' },
  { id: 'n5-12', category: 'N5语法', title: '那种人', subtitle: 'こんな、そんな、あんな、どんな', duration: '5m', initialPrompt: '教我日语的样态指示词：こんな、そんな、あんな、どんな。' },
  { id: 'n5-13', category: 'N5语法', title: '数数游戏', subtitle: '基数词', duration: '6m', initialPrompt: '教我日语基本的数字读法（基数词）。' },
  { id: 'n5-14', category: 'N5语法', title: '第一第二', subtitle: '序数词', duration: '4m', initialPrompt: '教我日语的序数词表达。' },
  { id: 'n5-15', category: 'N5语法', title: '量词大作战', subtitle: '常用助数词', duration: '8m', initialPrompt: '教我日语常用的量词（本、匹、个、台等）。' },
  { id: 'n5-16', category: 'N5语法', title: '到底有几个？', subtitle: '常用数量的读法', duration: '5m', initialPrompt: '教我日语数量词的特殊读音（比如一人、二人）。' },
  { id: 'n5-17', category: 'N5语法', title: '动词的三国演义', subtitle: '三类动词的区分', duration: '8m', initialPrompt: '教我如何区分日语的一类、二类和三类动词。' },
  { id: 'n5-18', category: 'N5语法', title: '自作自受？', subtitle: '自动词和他动词', duration: '8m', initialPrompt: '教我日语自动词和他动词的区别逻辑。' },
  { id: 'n5-19', category: 'N5语法', title: '变身！礼貌模式', subtitle: '动词「ます形」及敬体形', duration: '8m', initialPrompt: '教我日语动词的 Masu 形变形规则。' },
  { id: 'n5-20', category: 'N5语法', title: '万能胶水', subtitle: '动词「て形」', duration: '10m', initialPrompt: '教我日语动词最重要的 Te 形变形口诀。' },
  { id: 'n5-21', category: 'N5语法', title: '往事随风', subtitle: '动词「た形」', duration: '6m', initialPrompt: '教我日语动词的 Ta 形（简体过去式）。' },
  { id: 'n5-22', category: 'N5语法', title: '不许做！', subtitle: '动词「ない形」', duration: '6m', initialPrompt: '教我日语动词的 Nai 形（否定式）。' },
  { id: 'n5-23', category: 'N5语法', title: '切换频道', subtitle: '动词敬体形和普通形', duration: '5m', initialPrompt: '总结动词的敬体和简体切换。' },
  { id: 'n5-24', category: 'N5语法', title: '搞事情', subtitle: 'する', duration: '4m', initialPrompt: '讲解动词 する 的多种用法。' },
  { id: 'n5-25', category: 'N5语法', title: '搞一下', subtitle: 'やる', duration: '4m', initialPrompt: '讲解动词 やる 的用法及与 する 的区别。' },
  { id: 'n5-26', category: 'N5语法', title: 'Yes I Can', subtitle: 'できる', duration: '5m', initialPrompt: '讲解 できる (能够/完成) 的用法。' },
  { id: 'n5-27', category: 'N5语法', title: '这里有死物', subtitle: 'ある', duration: '5m', initialPrompt: '讲解存在动词 ある (无生命)。' },
  { id: 'n5-28', category: 'N5语法', title: '这里有活物', subtitle: 'いる', duration: '5m', initialPrompt: '讲解存在动词 いる (有生命)。' },
  { id: 'n5-29', category: 'N5语法', title: '那！就是那个形容词', subtitle: 'な形容词普通形', duration: '5m', initialPrompt: '教我日语的形容动词（Na形容词）的普通形。' },
  { id: 'n5-30', category: 'N5语法', title: '那！要礼貌', subtitle: 'な形容词敬体形', duration: '5m', initialPrompt: '教我日语的形容动词（Na形容词）的敬体形。' },
  { id: 'n5-31', category: 'N5语法', title: '漂亮的姑娘', subtitle: 'な形容词+名词', duration: '4m', initialPrompt: '教我 Na形容词如何修饰名词（加哪？）。' },
  { id: 'n5-32', category: 'N5语法', title: '既漂亮又聪明', subtitle: 'な形容词「て形」', duration: '5m', initialPrompt: '教我 Na形容词的中顿形（で）。' },
  { id: 'n5-33', category: 'N5语法', title: '变得漂亮', subtitle: 'な形容词+动词', duration: '5m', initialPrompt: '教我 Na形容词如何修饰动词（变成副词）。' },
  { id: 'n5-34', category: 'N5语法', title: '伊！是这个形容词', subtitle: 'い形容词普通形', duration: '5m', initialPrompt: '教我日语的 I形容词 普通形。' },
  { id: 'n5-35', category: 'N5语法', title: '伊！要礼貌', subtitle: 'い形容词敬体形', duration: '5m', initialPrompt: '教我日语的 I形容词 敬体形（加です）。' },
  { id: 'n5-36', category: 'N5语法', title: '可爱的猫', subtitle: 'い形容词+名词', duration: '4m', initialPrompt: '教我 I形容词 如何修饰名词。' },
  { id: 'n5-37', category: 'N5语法', title: '又高又帅', subtitle: 'い形容词「て形」', duration: '5m', initialPrompt: '教我 I形容词 的中顿形（くて）。' },
  { id: 'n5-38', category: 'N5语法', title: '走得快', subtitle: 'い形容词+动词', duration: '5m', initialPrompt: '教我 I形容词 如何修饰动词（变く）。' },
  { id: 'n5-39', category: 'N5语法', title: '几岁啦？', subtitle: 'いくつ', duration: '3m', initialPrompt: '讲解疑问词 いくつ (多少个/几岁)。' },
  { id: 'n5-40', category: 'N5语法', title: '何时君再来', subtitle: 'いつ', duration: '3m', initialPrompt: '讲解疑问词 いつ (什么时候)。' },
  { id: 'n5-41', category: 'N5语法', title: '那是谁？', subtitle: '誰/どの人/どなた/どの方', duration: '5m', initialPrompt: '讲解询问“谁”的四种不同礼貌程度的说法。' },
  { id: 'n5-42', category: 'N5语法', title: '怎么样？', subtitle: 'どう/いかが', duration: '4m', initialPrompt: '讲解询问意见或情况的 どう 和 いかが。' },
  { id: 'n5-43', category: 'N5语法', title: '大概多久？', subtitle: 'どのぐらい/どれぐらい', duration: '4m', initialPrompt: '讲解询问程度或时长的 どのぐらい。' },
  { id: 'n5-44', category: 'N5语法', title: '纳尼？！', subtitle: '何 (なに/なん)', duration: '5m', initialPrompt: '讲解 何 的读音区别（Nani vs Nan）。' },
  { id: 'n5-45', category: 'N5语法', title: '十万个为什么', subtitle: 'なぜ/どうして/なんで', duration: '5m', initialPrompt: '讲解三个“为什么”的区别。' },
  { id: 'n5-46', category: 'N5语法', title: '主语就是我', subtitle: 'が', duration: '6m', initialPrompt: '深入讲解助词 が 的用法（主语标记、对象语）。' },
  { id: 'n5-47', category: 'N5语法', title: '来自哪里', subtitle: 'から', duration: '5m', initialPrompt: '讲解助词 から (起点/原因)。' },
  { id: 'n5-48', category: 'N5语法', title: '用工具/在地点', subtitle: 'で', duration: '6m', initialPrompt: '深入讲解助词 で 的多种用法（工具、手段、动作场所）。' },
  { id: 'n5-49', category: 'N5语法', title: '我和你', subtitle: 'と', duration: '5m', initialPrompt: '讲解助词 と (并列、伴随、引用)。' },
  { id: 'n5-50', category: 'N5语法', title: '去哪里/几点', subtitle: 'に', duration: '6m', initialPrompt: '深入讲解助词 に (时间点、目的地、存在场所)。' },
  { id: 'n5-51', category: 'N5语法', title: '我的', subtitle: 'の', duration: '5m', initialPrompt: '讲解助词 の (所属、同位、修饰)。' },
  { id: 'n5-52', category: 'N5语法', title: '向着夕阳奔跑', subtitle: 'へ', duration: '4m', initialPrompt: '讲解助词 へ (移动方向) 及其读音。' },
  { id: 'n5-53', category: 'N5语法', title: '直到永远', subtitle: 'まで', duration: '4m', initialPrompt: '讲解助词 まで (终点)。' },
  { id: 'n5-54', category: 'N5语法', title: '把饭吃了', subtitle: 'を', duration: '5m', initialPrompt: '讲解助词 を (宾语标记、移动空间)。' },
  { id: 'n5-55', category: 'N5语法', title: '完全列举', subtitle: '～と～', duration: '3m', initialPrompt: '复习 と 的并列用法。' },
  { id: 'n5-56', category: 'N5语法', title: '不完全列举', subtitle: '～や～', duration: '4m', initialPrompt: '讲解 や (列举一部分)。' },
  { id: 'n5-57', category: 'N5语法', title: '或者', subtitle: '～か～', duration: '4m', initialPrompt: '讲解 か (选择/或者)。' },
  { id: 'n5-58', category: 'N5语法', title: '我也一样', subtitle: '～も', duration: '4m', initialPrompt: '讲解 も (也、强调)。' },
  { id: 'n5-59', category: 'N5语法', title: '话题的主角', subtitle: 'は', duration: '5m', initialPrompt: '复习助词 は (话题标记)。' },
  { id: 'n5-60', category: 'N5语法', title: '唯一的爱', subtitle: '～しか～ない', duration: '5m', initialPrompt: '讲解 しか...ない (只/仅，后接否定)。' },
  { id: 'n5-61', category: 'N5语法', title: '仅仅', subtitle: '～だけ', duration: '5m', initialPrompt: '讲解 だけ (只/仅，后接肯定)。' },
  { id: 'n5-62', category: 'N5语法', title: '大概齐', subtitle: '～くらい/ぐらい', duration: '4m', initialPrompt: '讲解 くらい/ぐらい (程度/概数)。' },
  { id: 'n5-63', category: 'N5语法', title: '等等', subtitle: '～など', duration: '4m', initialPrompt: '讲解 など (举例的省略)。' },
  { id: 'n5-64', category: 'N5语法', title: '虽然...但是...', subtitle: 'が (接续助词)', duration: '5m', initialPrompt: '讲解 が 作为接续助词表示转折（但是）。' },
  { id: 'n5-65', category: 'N5语法', title: '即使...也...', subtitle: 'ても/でも', duration: '5m', initialPrompt: '讲解 ても/でも (逆接条件)。' },
  { id: 'n5-66', category: 'N5语法', title: '不过...', subtitle: 'けれども/けど/けれど', duration: '5m', initialPrompt: '讲解口语中常用的转折 けれども。' },

  // --- N1 Lessons (198 Items) with Creative Titles ---
  { id: 'n1-1', category: 'N1语法', title: '全靠有你', subtitle: '~あっての', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~あっての」的用法。' },
  { id: 'n1-2', category: 'N1语法', title: '绝非他物', subtitle: '~以外の何ものでもない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~以外の何ものでもない」的用法。' },
  { id: 'n1-3', category: 'N1语法', title: '视情况而定', subtitle: '~いかんで/いかんでは...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~いかんで/いかんでは...」的用法。' },
  { id: 'n1-4', category: 'N1语法', title: '无论如何', subtitle: '~いかんにかかわらず...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~いかんにかかわらず...」的用法。' },
  { id: 'n1-5', category: 'N1语法', title: '紧要关头', subtitle: 'いざ~となると...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「いざ~となると...」的用法。' },
  { id: 'n1-6', category: 'N1语法', title: '差点火候', subtitle: '今ひとつ~(ない)', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「今ひとつ~(ない)」的用法。' },
  { id: 'n1-7', category: 'N1语法', title: '不言而喻', subtitle: '言わずもがな', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「言わずもがな」的用法。' },
  { id: 'n1-8', category: 'N1语法', title: '爱咋咋地', subtitle: '~(よ)うが/(よ)うと', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~(よ)うが/(よ)うと」的用法。' },
  { id: 'n1-9', category: 'N1语法', title: '无论A还是B', subtitle: '~(よ)うが~(よ)うが...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~(よ)うが~(よ)うが...」的用法。' },
  { id: 'n1-10', category: 'N1语法', title: '做不做都行', subtitle: '~(よ)うが~まいが...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~(よ)うが~まいが...」的用法。' },
  { id: 'n1-11', category: 'N1语法', title: '天塌下来', subtitle: '~(よ)うとも/くとも', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~(よ)うとも/くとも」的用法。' },
  { id: 'n1-12', category: 'N1语法', title: '有心无力', subtitle: '~(よ)うにも〜ない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~(よ)うにも〜ない」的用法。' },
  { id: 'n1-13', category: 'N1语法', title: '是耶非耶', subtitle: '~か否か', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~か否か」的用法。' },
  { id: 'n1-14', category: 'N1语法', title: '极致体验', subtitle: '~限りだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~限りだ」的用法。' },
  { id: 'n1-15', category: 'N1语法', title: '覆水难收', subtitle: '~が最後/たら最後', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~が最後/たら最後」的用法。' },
  { id: 'n1-16', category: 'N1语法', title: '一箭双雕', subtitle: '~かたがた', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~かたがた」的用法。' },
  { id: 'n1-17', category: 'N1语法', title: '一心二用', subtitle: '~かたわら', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~かたわら」的用法。' },
  { id: 'n1-18', category: 'N1语法', title: '顺道去办', subtitle: '~がてら', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~がてら」的用法。' },
  { id: 'n1-19', category: 'N1语法', title: '争分夺秒', subtitle: '~が早いか', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~が早いか」的用法。' },
  { id: 'n1-20', category: 'N1语法', title: '价值连城', subtitle: '~からある...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~からある...」的用法。' },
  { id: 'n1-21', category: 'N1语法', title: '有点毛病', subtitle: '~嫌いがある', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~嫌いがある」的用法。' },
  { id: 'n1-22', category: 'N1语法', title: '极其荒谬', subtitle: '~極まる/極まりない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~極まる/極まりない」的用法。' },
  { id: 'n1-23', category: 'N1语法', title: '宛如...', subtitle: '~ごとき...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ごとき...」的用法。' },
  { id: 'n1-24', category: 'N1语法', title: '毕竟是...', subtitle: '~ことだし', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ことだし」的用法。' },
  { id: 'n1-25', category: 'N1语法', title: '事出有因', subtitle: '~こととて', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~こととて」的用法。' },
  { id: 'n1-26', category: 'N1语法', title: '毫不...', subtitle: '~ことなしに', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ことなしに」的用法。' },
  { id: 'n1-27', category: 'N1语法', title: '以免...', subtitle: '~ことのないよう', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ことのないよう」的用法。' },
  { id: 'n1-28', category: 'N1语法', title: '原因之一', subtitle: '~こともあって', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~こともあって」的用法。' },
  { id: 'n1-29', category: 'N1语法', title: '悲惨结局', subtitle: '~始末だ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~始末だ」的用法。' },
  { id: 'n1-30', category: 'N1语法', title: '清一色', subtitle: '~ずくめ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ずくめ」的用法。' },
  { id: 'n1-31', category: 'N1语法', title: '没做成', subtitle: '~ずじまいだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ずじまいだ」的用法。' },
  { id: 'n1-32', category: 'N1语法', title: '绝不罢休', subtitle: '~ずにはおかない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ずにはおかない...」的用法。' },
  { id: 'n1-33', category: 'N1语法', title: '必须...', subtitle: '~ずにはすまない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ずにはすまない...」的用法。' },
  { id: 'n1-34', category: 'N1语法', title: '无计可施', subtitle: '~術がない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~術がない」的用法。' },
  { id: 'n1-35', category: 'N1语法', title: '甚至...', subtitle: '~(で)すら', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~(で)すら」的用法。' },
  { id: 'n1-36', category: 'N1语法', title: '随做随忘', subtitle: '~そばから', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~そばから」的用法。' },
  { id: 'n1-37', category: 'N1语法', title: '错失良机', subtitle: '~そびれる', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~そびれる」的用法。' },
  { id: 'n1-38', category: 'N1语法', title: '不止是你', subtitle: '(ひとり)~だけでなく...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「(ひとり)~だけでなく...」的用法。' },
  { id: 'n1-39', category: 'N1语法', title: '知足常乐', subtitle: '~だけましだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~だけましだ」的用法。' },
  { id: 'n1-40', category: 'N1语法', title: '唯有...', subtitle: 'ただ〜のみだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「ただ〜のみだ」的用法。' },
  { id: 'n1-41', category: 'N1语法', title: '也是白搭', subtitle: '~たところで', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~たところで」的用法。' },
  { id: 'n1-42', category: 'N1语法', title: '想都不敢想', subtitle: '~だに', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~だに」的用法。' },
  { id: 'n1-43', category: 'N1语法', title: '史无前例', subtitle: '~ためしがない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ためしがない」的用法。' },
  { id: 'n1-44', category: 'N1语法', title: '没完没了', subtitle: '~たらきりがない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~たらきりがない...」的用法。' },
  { id: 'n1-45', category: 'N1语法', title: '分毫之间', subtitle: '~たりとも', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~たりとも」的用法。' },
  { id: 'n1-46', category: 'N1语法', title: '既然是...', subtitle: '~たる/たるもの', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~たる/たるもの」的用法。' },
  { id: 'n1-47', category: 'N1语法', title: '此起彼伏', subtitle: '~つ〜つ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~つ〜つ」的用法。' },
  { id: 'n1-48', category: 'N1语法', title: '无论是谁', subtitle: '~であれ/であろうと', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~であれ/であろうと」的用法。' },
  { id: 'n1-49', category: 'N1语法', title: '无论AB', subtitle: '~であれ〜であれ...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~であれ〜であれ...」的用法。' },
  { id: 'n1-50', category: 'N1语法', title: '自从那次', subtitle: '~てからというもの', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~てからというもの」的用法。' },
  { id: 'n1-51', category: 'N1语法', title: '理所当然', subtitle: '~てしかるべきだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~てしかるべきだ」的用法。' },
  { id: 'n1-52', category: 'N1语法', title: '正是...', subtitle: '~でなくてなんだろう', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~でなくてなんだろう」的用法。' },
  { id: 'n1-53', category: 'N1语法', title: '又不是小孩', subtitle: '~ではあるまいし...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ではあるまいし...」的用法。' },
  { id: 'n1-54', category: 'N1语法', title: '实在受不了', subtitle: '~てはかなわない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~てはかなわない」的用法。' },
  { id: 'n1-55', category: 'N1语法', title: '反反复复', subtitle: '~ては〜ては', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ては〜ては」的用法。' },
  { id: 'n1-56', category: 'N1语法', title: '毫无顾忌', subtitle: '~て憚らない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~て憚らない」的用法。' },
  { id: 'n1-57', category: 'N1语法', title: '没法忍', subtitle: '~てはやりきれない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~てはやりきれない」的用法。' },
  { id: 'n1-58', category: 'N1语法', title: '甚至于...', subtitle: '~てまで', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~てまで」的用法。' },
  { id: 'n1-59', category: 'N1语法', title: '没关系', subtitle: '~ても差し支えない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ても差し支えない」的用法。' },
  { id: 'n1-60', category: 'N1语法', title: '万一...', subtitle: '~でもしたら', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~でもしたら」的用法。' },
  { id: 'n1-61', category: 'N1语法', title: '我才不管', subtitle: '~ても知らない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ても知らない」的用法。' },
  { id: 'n1-62', category: 'N1语法', title: '凭借...', subtitle: '~でもって', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~でもって」的用法。' },
  { id: 'n1-63', category: 'N1语法', title: '毫无办法', subtitle: '~てもどうにもならない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~てもどうにもならない...」的用法。' },
  { id: 'n1-64', category: 'N1语法', title: '不亏', subtitle: '~てもともとだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~てもともとだ」的用法。' },
  { id: 'n1-65', category: 'N1语法', title: '根本不是', subtitle: '~でも何でもない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~でも何でもない...」的用法。' },
  { id: 'n1-66', category: 'N1语法', title: '也没用', subtitle: '~ても始まらない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ても始まらない」的用法。' },
  { id: 'n1-67', category: 'N1语法', title: '衷心希望', subtitle: '~てやまない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~てやまない」的用法。' },
  { id: 'n1-68', category: 'N1语法', title: '双管齐下', subtitle: '~と(が)相まっても相まって', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~と(が)相まっても相まって」的用法。' },
  { id: 'n1-69', category: 'N1语法', title: '因为有...', subtitle: '~とあって', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とあって」的用法。' },
  { id: 'n1-70', category: 'N1语法', title: '若是...', subtitle: '~とあっては', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とあっては」的用法。' },
  { id: 'n1-71', category: 'N1语法', title: '既然是...', subtitle: '~とあれば', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とあれば」的用法。' },
  { id: 'n1-72', category: 'N1语法', title: '这个那个', subtitle: '~といい~といい', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~といい~といい」的用法。' },
  { id: 'n1-73', category: 'N1语法', title: '所谓的', subtitle: '~という', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~という」的用法。' },
  { id: 'n1-74', category: 'N1语法', title: '该说...', subtitle: '~というか〜というか', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~というか〜というか」的用法。' },
  { id: 'n1-75', category: 'N1语法', title: '顶多...', subtitle: '~というところだ...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~というところだ...」的用法。' },
  { id: 'n1-76', category: 'N1语法', title: '这段时间', subtitle: '~というもの', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~というもの」的用法。' },
  { id: 'n1-77', category: 'N1语法', title: '虽说...', subtitle: '~といえども', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~といえども」的用法。' },
  { id: 'n1-78', category: 'N1语法', title: '未尝不可', subtitle: '~と言えなくもない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~と言えなくもない」的用法。' },
  { id: 'n1-79', category: 'N1语法', title: '极其...', subtitle: '~といったらありはしない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~といったらありはしない...」的用法。' },
  { id: 'n1-80', category: 'N1语法', title: '并不是说', subtitle: '~といって〜ない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~といって〜ない...」的用法。' },
  { id: 'n1-81', category: 'N1语法', title: '不管...', subtitle: '~といわず~といわず', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~といわず~といわず」的用法。' },
  { id: 'n1-82', category: 'N1语法', title: '判若两人', subtitle: '~と(は)打って変わって', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~と(は)打って変わって」的用法。' },
  { id: 'n1-83', category: 'N1语法', title: '以为...其实', subtitle: '~(か)と思いきや', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~(か)と思いきや」的用法。' },
  { id: 'n1-84', category: 'N1语法', title: '提起...', subtitle: '~ときたら', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ときたら」的用法。' },
  { id: 'n1-85', category: 'N1语法', title: '正当...', subtitle: '~ところを', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ところを」的用法。' },
  { id: 'n1-86', category: 'N1语法', title: '竟然...', subtitle: '~としたことが', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~としたことが」的用法。' },
  { id: 'n1-87', category: 'N1语法', title: '就算是', subtitle: '~としたって...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~としたって...」的用法。' },
  { id: 'n1-88', category: 'N1语法', title: '作为一个...', subtitle: '~として〜ない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~作为...不」的用法。' },
  { id: 'n1-89', category: 'N1语法', title: '即使是...', subtitle: '~とて', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とて」的用法。' },
  { id: 'n1-90', category: 'N1语法', title: '竟然是', subtitle: '~とは/なんて', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とは/なんて」的用法。' },
  { id: 'n1-91', category: 'N1语法', title: '虽说如此', subtitle: '~とはいうものの...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とはいうものの...」的用法。' },
  { id: 'n1-92', category: 'N1语法', title: '尽管', subtitle: '~とはいえ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とはいえ」的用法。' },
  { id: 'n1-93', category: 'N1语法', title: '仿佛在说', subtitle: '~とばかりに', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とばかりに」的用法。' },
  { id: 'n1-94', category: 'N1语法', title: '虽不至于', subtitle: '~とまではいかないが...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とまではいかないが...」的用法。' },
  { id: 'n1-95', category: 'N1语法', title: '虽没说...', subtitle: '~とまでは言わないが...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~とまでは言わないが...」的用法。' },
  { id: 'n1-96', category: 'N1语法', title: '堂堂...', subtitle: '~ともあろうものが', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ともあろうものが」的用法。' },
  { id: 'n1-97', category: 'N1语法', title: '不经意间', subtitle: '~ともなく/ともなしに', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ともなく/ともなしに」的用法。' },
  { id: 'n1-98', category: 'N1语法', title: '一旦...', subtitle: '~ともなると...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ともなると...」的用法。' },
  { id: 'n1-99', category: 'N1语法', title: '历经...', subtitle: '~と/に~を重ねて', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~と/に~を重ねて」的用法。' },
  { id: 'n1-100', category: 'N1语法', title: '也不是不', subtitle: '~ないではない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ないではない/ないでもない」的用法。' },
  { id: 'n1-101', category: 'N1语法', title: '虽不至...', subtitle: '~ないまでも', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ないまでも」的用法。' },
  { id: 'n1-102', category: 'N1语法', title: '也有可能', subtitle: '~ないものでもない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ないものでもない」的用法。' },
  { id: 'n1-103', category: 'N1语法', title: '保持...', subtitle: '~ながらに/ながらの', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ながらに/ながらの」的用法。' },
  { id: 'n1-104', category: 'N1语法', title: '虽然...', subtitle: '~ながらも', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ながらも」的用法。' },
  { id: 'n1-105', category: 'N1语法', title: '若无...', subtitle: '~なくして(は)', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~なくして(は)」的用法。' },
  { id: 'n1-106', category: 'N1语法', title: '并非没有', subtitle: '~なくはない/なくもない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~なくはない/なくもない」的用法。' },
  { id: 'n1-107', category: 'N1语法', title: '没有...就', subtitle: '~なしに/なしには...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~なしに/なしには...」的用法。' },
  { id: 'n1-108', category: 'N1语法', title: '另当别论', subtitle: '~ならいざしらず', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ならいざしらず」的用法。' },
  { id: 'n1-109', category: 'N1语法', title: '独有特色', subtitle: '~ならでは/ならではの', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ならでは/ならではの」的用法。' },
  { id: 'n1-110', category: 'N1语法', title: '刚一...', subtitle: '~なり', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~なり」的用法。' },
  { id: 'n1-111', category: 'N1语法', title: '哪怕是...', subtitle: '~なりとも', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~なりとも」的用法。' },
  { id: 'n1-112', category: 'N1语法', title: '或是...', subtitle: '~なり~なり', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~なり~なり」的用法。' },
  { id: 'n1-113', category: 'N1语法', title: '相应的', subtitle: '~なりに/なりの', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~なりに/なりの」的用法。' },
  { id: 'n1-114', category: 'N1语法', title: '值得', subtitle: '~に値する/に値しない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に値する/に値しない」的用法。' },
  { id: 'n1-115', category: 'N1语法', title: '不必...', subtitle: '~に(は)あたらない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に(は)あたらない」的用法。' },
  { id: 'n1-116', category: 'N1语法', title: '处于...', subtitle: '~にあって(は)...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にあって(は)/にあっても」的用法。' },
  { id: 'n1-117', category: 'N1语法', title: '至于...', subtitle: '~に至って...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に至って...」的用法。' },
  { id: 'n1-118', category: 'N1语法', title: '上至...', subtitle: '~に至るまで', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に至るまで」的用法。' },
  { id: 'n1-119', category: 'N1语法', title: '多亏', subtitle: '~に負うところが多い...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に負うところが多い...」的用法。' },
  { id: 'n1-120', category: 'N1语法', title: '关于', subtitle: '~におかれましては', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~におかれましては」的用法。' },
  { id: 'n1-121', category: 'N1语法', title: '不必', subtitle: '~に(は)及ばない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に(は)及ばない」的用法。' },
  { id: 'n1-122', category: 'N1语法', title: '必不可少', subtitle: '~に欠かせない...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に欠かせない...」的用法。' },
  { id: 'n1-123', category: 'N1语法', title: '说到...', subtitle: '~にかかったら...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にかかったら...」的用法。' },
  { id: 'n1-124', category: 'N1语法', title: '取决于', subtitle: '~にかかっている', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にかかっている」的用法。' },
  { id: 'n1-125', category: 'N1语法', title: '不仅是', subtitle: '~に限ったことではない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に限ったことではない」的用法。' },
  { id: 'n1-126', category: 'N1语法', title: '借口', subtitle: '~にかこつけて', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にかこつけて」的用法。' },
  { id: 'n1-127', category: 'N1语法', title: '不难', subtitle: '~にかたくない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にかたくない」的用法。' },
  { id: 'n1-128', category: 'N1语法', title: '忙于', subtitle: '~にかまけて', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にかまけて」的用法。' },
  { id: 'n1-129', category: 'N1语法', title: '最好不过', subtitle: '~に越したことはない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に越したことはない」的用法。' },
  { id: 'n1-130', category: 'N1语法', title: '莫过于', subtitle: '~に如くはない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に如くはない」的用法。' },
  { id: 'n1-131', category: 'N1语法', title: '既是...', subtitle: '~にして', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にして」的用法。' },
  { id: 'n1-132', category: 'N1语法', title: '不忍', subtitle: '~に忍びない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に忍びない」的用法。' },
  { id: 'n1-133', category: 'N1语法', title: '按照', subtitle: '~に準じ...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に準じ/に準じて...」的用法。' },
  { id: 'n1-134', category: 'N1语法', title: '结合', subtitle: '~に即して...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に即して...」的用法。' },
  { id: 'n1-135', category: 'N1语法', title: '不堪', subtitle: '~にたえる/にたえない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にたえる/にたえない」的用法。' },
  { id: 'n1-136', category: 'N1语法', title: '足以', subtitle: '~に足りる/に足る', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に足りる/に足る」的用法。' },
  { id: 'n1-137', category: 'N1语法', title: '不值', subtitle: '~に足りない/に足らない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に足りない/に足らない」的用法。' },
  { id: 'n1-138', category: 'N1语法', title: '对照', subtitle: '~に照らして', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に照らして」的用法。' },
  { id: 'n1-139', category: 'N1语法', title: '不止', subtitle: '~にとどまらず', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にとどまらず」的用法。' },
  { id: 'n1-140', category: 'N1语法', title: '依照', subtitle: '~に則って', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~に則って」的用法。' },
  { id: 'n1-141', category: 'N1语法', title: '有点勉强', subtitle: '~には無理がある', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~には無理がある」的用法。' },
  { id: 'n1-142', category: 'N1语法', title: '相比之下', subtitle: '~にひきかえ...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にひきかえ...」的用法。' },
  { id: 'n1-143', category: 'N1语法', title: '太过分', subtitle: '~にもほどがある', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にもほどがある」的用法。' },
  { id: 'n1-144', category: 'N1语法', title: '胜过', subtitle: '~にも増して', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~にも増して」的用法。' },
  { id: 'n1-145', category: 'N1语法', title: '全赖', subtitle: '~によるところが大きい', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~によるところが大きい」的用法。' },
  { id: 'n1-146', category: 'N1语法', title: '极其', subtitle: '~の至りだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~の至りだ」的用法。' },
  { id: 'n1-147', category: 'N1语法', title: '极限', subtitle: '~の極みだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~の極みだ」的用法。' },
  { id: 'n1-148', category: 'N1语法', title: '...什么的', subtitle: '~のなんの', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~のなんの」的用法。' },
  { id: 'n1-149', category: 'N1语法', title: '不仅', subtitle: '(ただ)~のみならず...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「(ただ)~のみならず...」的用法。' },
  { id: 'n1-150', category: 'N1语法', title: '别说...', subtitle: '~はおろか', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~はおろか」的用法。' },
  { id: 'n1-151', category: 'N1语法', title: '正因为', subtitle: '~ばこそ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ばこそ」的用法。' },
  { id: 'n1-152', category: 'N1语法', title: '暂且不论', subtitle: '~はさておき...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~はさておき...」的用法。' },
  { id: 'n1-153', category: 'N1语法', title: '一刹那', subtitle: '~弾み', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~弾み」的用法。' },
  { id: 'n1-154', category: 'N1语法', title: '不顾', subtitle: '~はそっちのけで...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~はそっちのけで...」的用法。' },
  { id: 'n1-155', category: 'N1语法', title: '...就完了', subtitle: '~ばそれまでだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ばそれまでだ」的用法。' },
  { id: 'n1-156', category: 'N1语法', title: '落得...', subtitle: '~羽目になる...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~羽目になる...」的用法。' },
  { id: 'n1-157', category: 'N1语法', title: '禁止', subtitle: '~べからず/べからざる', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~べからず/べからざる」的用法。' },
  { id: 'n1-158', category: 'N1语法', title: '为了', subtitle: '~べく', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~べく」的用法。' },
  { id: 'n1-159', category: 'N1语法', title: '注定', subtitle: '~べくして', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~べくして」的用法。' },
  { id: 'n1-160', category: 'N1语法', title: '无法', subtitle: '~べくもない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~べくもない」的用法。' },
  { id: 'n1-161', category: 'N1语法', title: '不该', subtitle: '~まじき', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~まじき」的用法。' },
  { id: 'n1-162', category: 'N1语法', title: '甚至', subtitle: '~までして', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~までして」的用法。' },
  { id: 'n1-163', category: 'N1语法', title: '只是', subtitle: '~までだ/までのことだ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~までだ/までのことだ」的用法。' },
  { id: 'n1-164', category: 'N1语法', title: '用不着', subtitle: '~までもなく/までもない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~までもなく/までもない」的用法。' },
  { id: 'n1-165', category: 'N1语法', title: '满身', subtitle: '~まみれ', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~まみれ」的用法。' },
  { id: 'n1-166', category: 'N1语法', title: '带有...味', subtitle: '~めく', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~めく」的用法。' },
  { id: 'n1-167', category: 'N1语法', title: '不顾', subtitle: '~も顧みず/を顧みず', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~も顧みず/を顧みず」的用法。' },
  { id: 'n1-168', category: 'N1语法', title: '固然', subtitle: '~もさることながら', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~もさることながら」的用法。' },
  { id: 'n1-169', category: 'N1语法', title: '如同', subtitle: '~も同然だ/も同然の', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~も同然だ/も同然の」的用法。' },
  { id: 'n1-170', category: 'N1语法', title: '被认为', subtitle: '~ものと思われる', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ものと思われる」的用法。' },
  { id: 'n1-171', category: 'N1语法', title: '明明', subtitle: '~ものを', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ものを」的用法。' },
  { id: 'n1-172', category: 'N1语法', title: '刚一', subtitle: '~や/や否や', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~や/や否や」的用法。' },
  { id: 'n1-173', category: 'N1语法', title: '正当', subtitle: '~矢先に', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~矢先に」的用法。' },
  { id: 'n1-174', category: 'N1语法', title: '绝不', subtitle: '~やしない/はしない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~やしない/はしない」的用法。' },
  { id: 'n1-175', category: 'N1语法', title: '又是', subtitle: 'やれ〜やれ~', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「やれ〜やれ~」的用法。' },
  { id: 'n1-176', category: 'N1语法', title: '之所以', subtitle: '~(が)ゆえ(に)...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~(が)ゆえ(に)...」的用法。' },
  { id: 'n1-177', category: 'N1语法', title: '全看', subtitle: '~ようによっては', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~ようによっては」的用法。' },
  { id: 'n1-178', category: 'N1语法', title: '除了', subtitle: '~をおいて', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~をおいて」的用法。' },
  { id: 'n1-179', category: 'N1语法', title: '顶着', subtitle: '~を押して...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を押して...」的用法。' },
  { id: 'n1-180', category: 'N1语法', title: '截止', subtitle: '~を限りに', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を限りに」的用法。' },
  { id: 'n1-181', category: 'N1语法', title: '以...为首', subtitle: '~を皮切りに(して)', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を皮切りに(して)」的用法。' },
  { id: 'n1-182', category: 'N1语法', title: '契机', subtitle: '~を機に', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を機に」的用法。' },
  { id: 'n1-183', category: 'N1语法', title: '不禁', subtitle: '~を禁じ得ない', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を禁じ得ない」的用法。' },
  { id: 'n1-184', category: 'N1语法', title: '轻视', subtitle: '~を蔑ろにする', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を蔑ろにする」的用法。' },
  { id: 'n1-185', category: 'N1语法', title: '忽视', subtitle: '~をなおざりにして', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~をなおざりにして」的用法。' },
  { id: 'n1-186', category: 'N1语法', title: '面临', subtitle: '~を控え...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を控え...」的用法。' },
  { id: 'n1-187', category: 'N1语法', title: '基于', subtitle: '~を踏まえ...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を踏まえ...」的用法。' },
  { id: 'n1-188', category: 'N1语法', title: '以...开始', subtitle: '~を振り出しに', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を振り出しに」的用法。' },
  { id: 'n1-189', category: 'N1语法', title: '经过', subtitle: '~を経て', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を経て」的用法。' },
  { id: 'n1-190', category: 'N1语法', title: '以此', subtitle: '~をもって...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~をもって...」的用法。' },
  { id: 'n1-191', category: 'N1语法', title: '无视', subtitle: '~をものともせずに', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~をものともせずに」的用法。' },
  { id: 'n1-192', category: 'N1语法', title: '迫使', subtitle: '~を余儀なくさせる', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を余儀なくさせる」的用法。' },
  { id: 'n1-193', category: 'N1语法', title: '被迫', subtitle: '~を余儀なくされる', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~を余儀なくされる」的用法。' },
  { id: 'n1-194', category: 'N1语法', title: '不顾', subtitle: '~をよそに', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~をよそに」的用法。' },
  { id: 'n1-195', category: 'N1语法', title: '为了', subtitle: '~んがため...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~んがため(に)...」的用法。' },
  { id: 'n1-196', category: 'N1语法', title: '早知不', subtitle: '~んじゃなかった', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~んじゃなかった」的用法。' },
  { id: 'n1-197', category: 'N1语法', title: '听说', subtitle: '~んだって/んですって', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~んだって/んですって」的用法。' },
  { id: 'n1-198', category: 'N1语法', title: '眼看', subtitle: '~んばかりに...', duration: '5m', initialPrompt: 'Sensei, 请教我 N1 语法点「~んばかりに...」的用法。' },
];

export const PREDEFINED_LESSONS = lessons;

export const DEFAULT_SUGGESTIONS: SuggestedReply[] = [
  { label: '给个例句', value: '请给我一个地道的例句 ✨' },
  { label: '怎么接续', value: '这个语法前面接什么词性？ 🤔' },
  { label: '易错点', value: '有什么需要注意的易错点吗？ ⚠️' },
];
