
import React from 'react';
import { X, Search, BookOpen, Loader2 } from 'lucide-react';
import { MarkdownRenderer } from './MarkdownRenderer';

interface ExplanationPanelProps {
  isOpen: boolean;
  onClose: () => void;
  loading: boolean;
  query: string;
  result: string | null;
  ttsSpeed: number;
  onExplainNested?: (text: string) => void;
}

export const ExplanationPanel: React.FC<ExplanationPanelProps> = ({ 
  isOpen, 
  onClose, 
  loading, 
  query, 
  result,
  ttsSpeed,
  onExplainNested
}) => {
  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div 
            className="fixed inset-0 bg-blue-950/20 backdrop-blur-sm z-50 transition-opacity"
            onClick={onClose}
        ></div>
      )}

      {/* Drawer */}
      <div className={`fixed top-0 right-0 h-full w-[90%] max-w-md bg-white border-l-[3px] border-blue-950 shadow-2xl z-[60] transform transition-transform duration-300 ease-in-out font-hand ${isOpen ? 'translate-x-0' : 'translate-x-full'}`}>
        
        {/* Header */}
        <div className="bg-blue-600 p-4 border-b-[3px] border-blue-950 flex items-center justify-between">
            <div className="flex items-center gap-2 text-white">
                <BookOpen size={20} strokeWidth={3} className="text-white" />
                <h2 className="text-xl font-black">深度解析</h2>
            </div>
            <button 
                onClick={onClose}
                className="bg-blue-500 p-1 rounded-lg border-2 border-blue-950 text-white hover:bg-red-400 transition-colors shadow-sketchy-sm active:translate-y-0.5 active:shadow-none"
            >
                <X size={20} strokeWidth={3} />
            </button>
        </div>

        {/* Content */}
        <div className="p-4 h-[calc(100%-68px)] overflow-y-auto hide-scrollbar bg-white">
            
            {/* Query Section */}
            <div className="mb-6">
                <div className="text-xs font-bold text-blue-400 uppercase tracking-wide mb-2 flex items-center gap-1">
                    <Search size={12} /> 查询对象
                </div>
                <div className="text-2xl font-black text-blue-950 border-l-4 border-blue-500 pl-4 py-1 leading-relaxed">
                    {query}
                </div>
            </div>

            {/* Result Section */}
            {loading ? (
                <div className="flex flex-col items-center justify-center py-12 space-y-4 animate-pulse">
                    <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center border-2 border-blue-200">
                        <Loader2 size={24} className="animate-spin text-blue-500" strokeWidth={3} />
                    </div>
                    <p className="text-blue-400 font-bold">Sensei 正在查阅词典...</p>
                </div>
            ) : result ? (
                <div className="animate-[fadeIn_0.3s_ease-out]">
                    <div className="markdown-body text-blue-900 leading-7">
                        <MarkdownRenderer 
                            markdownText={result} 
                            ttsSpeed={ttsSpeed}
                            onExplain={onExplainNested} // Allow recursive explanations
                            collectedSentences={[]} // Not strictly needed here, but keeps props consistent
                        />
                    </div>
                </div>
            ) : (
                <div className="text-center text-gray-400 py-10 font-bold">
                    暂无解析内容
                </div>
            )}
            
            {/* Footer / Decor */}
            {!loading && result && (
                <div className="mt-8 pt-4 border-t-2 border-dashed border-gray-100 text-center">
                    <span className="text-[10px] text-gray-300 font-bold">Generated by Grammar Sensei Dictionary</span>
                </div>
            )}
        </div>
      </div>
    </>
  );
};
